name: ci

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - sdk: '8.0.x'
            tfm: 'net8.0'
          - sdk: '9.0.x'
            tfm: 'net9.0'
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET ${{ matrix.sdk }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.sdk }}
          cache: true
          cache-dependency-path: |
            **/packages.lock.json
            **/*.csproj
            **/NuGet.config

      - run: dotnet --info

      - run: dotnet restore -p:TargetFramework=${{ matrix.tfm }}
      - run: dotnet build -c Release --no-restore -p:TargetFramework=${{ matrix.tfm }}
      - run: dotnet test -c Release --no-build    -p:TargetFramework=${{ matrix.tfm }}

  pack_publish:
    runs-on: ubuntu-latest
    needs: build_test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Compute package version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "PKG_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          cache: true
          cache-dependency-path: |
            **/packages.lock.json
            **/*.csproj
            **/NuGet.config
      - run: dotnet restore
      - run: dotnet pack ./src/Feathery.Unofficial.Client.csproj -c Release -o ./artifacts -p:Version=${{ env.PKG_VERSION }} -p:ContinuousIntegrationBuild=true
      - name: Publish NuGet
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate